inbound:
  env: production
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: false
  tasks:
    reportPipeline:
      - country: FR
        language: FR
      - country: US
        language: EN

outbound:
  agents:
    reportIngestion: 'openai/gpt-oss-120b'
    reportDeduplication: 'deepseek/deepseek-chat-v3-0324'
    reportClassification: 'deepseek/deepseek-chat-v3-0324'
    articleComposition: 'google/gemini-2.5-flash'
    articleFabrication: 'google/gemini-2.5-flash'
    articleQuizGeneration: 'google/gemini-2.5-flash'

  worldNews:
    useCache: false
  newRelic:
    enabled: true
