inbound:
  env: production
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: false
  tasks:
    reportPipeline:
      - country: FR
        language: FR
      - country: US
        language: EN

outbound:
  prisma:
    databaseUrl: file:./database/main.sqlite

  agents:
    reportIngestion: 'deepseek/deepseek-v3.2'
    reportDeduplication: 'deepseek/deepseek-v3.2'
    reportClassification: 'deepseek/deepseek-v3.2'
    articleComposition: 'google/gemini-3-pro-preview'
    articleFabrication: 'x-ai/grok-4-fast'
    articleQuizGeneration: 'x-ai/grok-4-fast'

  worldNews:
    useCache: false
  telemetry:
    enabled: true
