inbound:
  http:
    port: 3000
  logger:
    level: debug
    prettyPrint: true
  tasks:
    reportPipeline:
      - country: FR
        language: FR

outbound:
  agents:
    reportIngestion: 'google/gemini-2.5-flash-lite'
    reportDeduplication: 'google/gemini-2.5-flash-lite'
    reportClassification: 'google/gemini-2.5-flash-lite'
    articleComposition: 'google/gemini-2.5-flash-lite'
    articleFabrication: 'google/gemini-2.5-flash-lite'
    articleQuizGeneration: 'google/gemini-2.5-flash-lite'

  worldNews:
    useCache: true
